global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#sergey_reshetnikov'
